SELECT A.AUTHOR_ID, A.AUTHOR_NAME, S.CATEGORY, S.TOTAL_SALES
FROM AUTHOR A
JOIN (
    SELECT B.AUTHOR_ID, B.CATEGORY, SUM(B.PRICE * S.SALES) AS TOTAL_SALES
    FROM BOOK B
    JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
    WHERE S.SALES_DATE LIKE '2022-01%'
    GROUP BY B.AUTHOR_ID, B.CATEGORY
) AS S ON A.AUTHOR_ID = S.AUTHOR_ID
ORDER BY A.AUTHOR_ID, S.CATEGORY DESC

# SELECT * FROM BOOK_SALES S
# JOIN BOOK B ON B.BOOK_ID = S.BOOK_ID