SELECT P.PRODUCT_ID, P.PRODUCT_NAME, PRICE * SUM(AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS P JOIN (
    SELECT *
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE LIKE '2022-05%'
) AS O ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID