SELECT SQ.APNT_NO, P.PT_NAME, SQ.PT_NO, SQ.MCDP_CD, SQ.DR_NAME, SQ.APNT_YMD
FROM PATIENT AS P JOIN (
    SELECT SQ.APNT_NO, SQ.PT_NO, D.MCDP_CD, D.DR_NAME, SQ.APNT_YMD
    FROM DOCTOR AS D JOIN (
        SELECT APNT_NO, PT_NO, MDDR_ID, APNT_YMD
        FROM APPOINTMENT
        WHERE APNT_YMD LIKE '2022-04-13%' AND APNT_CNCL_YN = 'N'
    ) AS SQ ON D.DR_ID = SQ.MDDR_ID
) AS SQ ON P.PT_NO = SQ.PT_NO
ORDER BY SQ.APNT_YMD