# SELECT HOUR(DATETIME) HOUR, COUNT(*) COUNT
# FROM ANIMAL_OUTS
# GROUP BY HOUR
# ORDER BY HOUR

WITH RECURSIVE RC AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM RC
    WHERE HOUR < 23
)

SELECT RC.HOUR, COUNT(A.ANIMAL_ID) COUNT
FROM RC LEFT JOIN ANIMAL_OUTS A
ON RC.HOUR = HOUR(A.DATETIME)
GROUP BY RC.HOUR
ORDER BY RC.HOUR