SELECT M.MEMBER_NAME, SQ.REVIEW_TEXT, 
DATE_FORMAT(SQ.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM MEMBER_PROFILE M
JOIN (
    SELECT *
    FROM REST_REVIEW AS R
    WHERE MEMBER_ID = (
        SELECT MEMBER_ID
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(*) DESC
        LIMIT 1
    )
) SQ ON M.MEMBER_ID = SQ.MEMBER_ID
ORDER BY SQ.REVIEW_DATE, SQ.REVIEW_TEXT